### ISSUE TITLE
New ToDo's for Altis Life Mission

### ISSUE THREAD

**Issue by DevVersion** [DevVersion/AltisLifeMod#6]
- [x] Flying Table at the Kavala Marketplace
- [x] Step bug at Kavala Marketplace.
- [x] Police Car Garage Sell Bug.
- [x] Q Farming Hotkey
- [x] Respawn Gear Bug.
- [x] Server restart script. 
- [x] Adding a parking lot near Kavala Marketplace.
- [x] Death bug when disconnect.
- [x] Editing Garage message if you have no vehicles in it. From "Keine Fahrzeuge in der Garage gefunden" to "Keine Fahrzeuge in der Garage"
- [x] Icons Black in Shops
- [x] Changing sell price of the hummingbird helicopter of the ADACs.
- [x] If a ADAC tow a vehicle with his own car and he release it, the car bugs through the map and explode. 
- [x] Adding a window with the Teamspeak IP to the map menu.

**Comment by TheReffels** [comment]
If you want to sell a car in the Garage at the Police Station, you only got 5000 Dollars.

**Comment by TheReffels** [comment]
Flying Table at the Kavala Marketplace

**Comment by TheReffels** [comment]
Step bug at Kavala Marketplace.

**Comment by TheReffels** [comment]
- [ ] Car Garage Sell Bug

**Comment by TheReffels** [comment]
- [ ] Respawn gear bug.

**Comment by TheReffels** [comment]
Adding a List of Players at bottom right corner. With: Zivilists, Polices, ADACs, Medics.

**Comment by TheReffels** [comment]
- [ ] Server restart scrtipt.

**Comment by TheReffels** [comment]
- [ ] Adding a Money Transporter for the Rebbels to rob.

**Comment by TheReffels** [comment]
- [ ] Adding a parking lot near Kavala Marketplace.

**Comment by TheReffels** [comment]
- [ ] Police Market man ist Standing a bit in the ground.

**Comment by TheReffels** [comment]
- [ ] Adding a Window when joining the Server with the Server rules.

**Comment by TheReffels** [comment]
- [ ] Changing Police Symbol on the map.

**Comment by TheReffels** [comment]
- [ ] Death bug when disconnect.

**Comment by TheReffels** [comment]
- [ ] Editing Garage message if you have no vehicles in it. From "Keine Fahrzeuge in der Garage gefunden" to "Keine Fahrzeuge in der Garage"

**Comment by TheReffels** [comment]
- [ ] Adding a spawnpoint for the last position.

**Comment by TheReffels** [comment]
- [ ] Adding the menu for the post office man.

**Comment by PaulGap** [comment]
- [ ] ADAC Vehicle Virtual Item Store

**Comment by TheReffels** [comment]
- [ ] Editing Z Message for keys. From "Schlüsselbund" to "Schlüssel"

**Comment by TheReffels** [comment]
- [ ] Editing Texture for higher Ranks of bigger Backpacks. It should be a police texture.

**Comment by TheReffels** [comment]
- [ ] Adding a list for the Players with all things you can do with your rank.

**Comment by TheReffels** [comment]
- [ ] You can farm apples and plums at the tree's.

**Comment by PaulGap** [comment]
- [ ] Icons Black in Shops

**Comment by TheReffels** [comment]
- [ ] Fixing the bug that if you close the cloth shop and you have selected a cloth you take it with you. This only happens with the ADAC class.
- [ ] If a ADAC tow his own car he got 30.000. Players shouldn't get Money if they tow his own vehicle.

**Comment by TheReffels** [comment]
- [ ] Adding a savezone at the Kavala Marketplace

**Comment by TheReffels** [comment]
- [ ] Zivilists could unlock People.
- [ ] Zivilist should not leave the vehicle if they're locked.

**Comment by TheReffels** [comment]
- [ ] If you park your vehicle in the Garage you loose all the stuff in it.

**Comment by TheReffels** [comment]
- [ ] Changing sell price of the hummingbird helicopter of the ADACs.

**Comment by TheReffels** [comment]
If a ADAC tow a vehicle with his own car and he release it, the car bugs through the map and explode.

**Comment by TheReffels** [comment]
- [ ] Hotkey farming. Q.

**Comment by TheReffels** [comment]
- [ ] If a ADAC is Online only he could tow cars. But if no ADACs are online policemans could do this.

**Comment by TheReffels** [comment]
- [ ] Paul

**Comment by TheReffels** [comment]
- [ ] Adding a Feature that policeman could build roadblocks. Like Nailbans.

**Comment by TheReffels** [comment]
- [ ] Adding a window with the Teamspeak IP to the map menu.

**Comment by TheReffels** [comment]
- [ ] Locking Auto-Clicker.

**Comment by TheReffels** [comment]
- [ ] ADAC Symbol.

**Comment by TheReffels** [comment]
- [ ] Setting down the prise if you take a car from your Garage.

**Comment by TheReffels** [comment]
- [ ] ADAC and Police Placement Features

**Comment by PaulGap** [comment]
- [ ] Credits for Users

**Comment by PaulGap** [comment]
- [ ] Turtle Prices -> Prices of Items

**Comment by PaulGap** [comment]
- [ ] Adding cable Ties to the rebbels shop.
- [ ] Adding Morphium to the Medics.

**Comment by DasFlugeug** [comment]
Ideen für den Altis Server XLive

-UAV Drohnen Kontrolle
-Rebellen Bananenhelikopter
-Hellcat für Rebellen
-Alamut
-Clanbasen
-besondere Tarnungen für cläne
-besondere waffen für cläne
-stellt mich beim sek ein :D 
-Events
-Goldtransporte
-Support channel im TS
-Ts mehr geordnet
-Sek Base (unbekannt)
-Hunter für Rebellen
-strider für Rebellen

## -Neue Mg´s
